networks:
  monitoring:
    driver: bridge

services:
  sample-api-1:
    image: sample-api
    container_name: sample-api-1
    build:
      context: .
      dockerfile: FailoverSample/Dockerfile
    ports:
      - 6101:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceName=Service1
    networks:
      - monitoring